application:
  solver:
    default-solver-time-limit-in-sec: 60

spring:
  mustache:
    check-template-location: false
  datasource:
    url: jdbc:h2:file:./h2-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  task:
    execution:
      thread-name-prefix: "Thread #"

logging:
  level:
    root: INFO
    org.atmosphere: WARN
    com.cocroachden.planner: DEBUG

vaadin:
  launch-browser: false